title: Rail Analysis System
description: Interactive rail defect analysis system
theme: jekyll-theme-primer
baseurl: ""
url: "https://yanis2002.github.io/Rels.github.io"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-github-metadata
defaults:
  - scope:
      path: ""
    values:
      layout: default 